### ISSUE TITLE
How to test for the constant treatment effect

### ISSUE THREAD

**Issue by syj1997104** [hwj0828/CSTE#1]
**How to test for the constant treatment effect?**
i want to test for the null hypothesis ,after  reading the references ,i have a doubt that whether  CSTE-package has a function to  achieve this function.Cuz i did not found any code to test for this. IF you can give me an answear ,i will appreciate it very much!!

**Comment by hwj0828** [comment]
Hi, thanks for your question. But sorry that the CSTE package currently doesn't have this kind function. We may consider that in the future.

Best,

Wenjie



-----Original Messages-----
From:syj1997104 ***@***.***>
Sent Time:2021-09-30 10:37:49 (Thursday)
To: hwj0828/CSTE ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [hwj0828/CSTE] How to test for the constant treatment effect (#1)






How to test for the constant treatment effect?
i want to test for the null hypothesis ,after reading the references ,i have a doubt that whether CSTE-package has a function to achieve this function.Cuz i did not found any code to test for this. IF you can give me an answear ,i will appreciate it very much!!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.




Wenjie Hu
School of Mathematical Science of Peking University
Tel: (+86)18811525113    Zip Code:100871
Address: 63 Building, Peking University, Haidian District, Beijing, P.R.China

**Comment by hwj0828** [comment]
Hi, thanks for your question. But sorry that the CSTE package currently doesn't have this kind function. We may consider that in the future.

**Comment by syj1997104** [comment]
Thanks for your answer，maybe i should find another way to solve my promble.Thanks again !!!
